add_test([=[CmdArgsTest.EmptyArgs]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.EmptyArgs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.EmptyArgs]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.LongOptionWithValue]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.LongOptionWithValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.LongOptionWithValue]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.LongOptionWithEquals]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.LongOptionWithEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.LongOptionWithEquals]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.LongOptionEmptyValue]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.LongOptionEmptyValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.LongOptionEmptyValue]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.LongOptionWithoutValue]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.LongOptionWithoutValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.LongOptionWithoutValue]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.ShortOptionWithValue]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.ShortOptionWithValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.ShortOptionWithValue]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.ShortOptionWithEquals]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.ShortOptionWithEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.ShortOptionWithEquals]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.ShortOptionEmptyValue]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.ShortOptionEmptyValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.ShortOptionEmptyValue]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.ShortOptionWithoutValue]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.ShortOptionWithoutValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.ShortOptionWithoutValue]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.GroupedShortOptions]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.GroupedShortOptions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.GroupedShortOptions]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.PositionalArguments]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.PositionalArguments]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.PositionalArguments]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.MixedOptionsAndPositionals]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.MixedOptionsAndPositionals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.MixedOptionsAndPositionals]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.DuplicateKeys]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.DuplicateKeys]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.DuplicateKeys]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.LongOptionWithSpacedEquals]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.LongOptionWithSpacedEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.LongOptionWithSpacedEquals]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.ShortOptionWithSpacedEquals]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.ShortOptionWithSpacedEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.ShortOptionWithSpacedEquals]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.ValueStartingWithDash]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.ValueStartingWithDash]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.ValueStartingWithDash]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.EmptyStringValue]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.EmptyStringValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.EmptyStringValue]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.MultipleOptionsAndValues]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.MultipleOptionsAndValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.MultipleOptionsAndValues]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.WhitespaceInValues]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.WhitespaceInValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.WhitespaceInValues]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.SpecialCharactersInValues]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.SpecialCharactersInValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.SpecialCharactersInValues]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.RealWorldExample_Generate]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.RealWorldExample_Generate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.RealWorldExample_Generate]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.RealWorldExample_Sign]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.RealWorldExample_Sign]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.RealWorldExample_Sign]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.RealWorldExample_Verify]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.RealWorldExample_Verify]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.RealWorldExample_Verify]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.NonexistentOption]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.NonexistentOption]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.NonexistentOption]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CmdArgsTest.ConsistencyBetweenLongAndShortEquals]=]  /Users/steve/src/jwt-cpp/build-auto/cmd_args_test [==[--gtest_filter=CmdArgsTest.ConsistencyBetweenLongAndShortEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CmdArgsTest.ConsistencyBetweenLongAndShortEquals]=]  PROPERTIES WORKING_DIRECTORY /Users/steve/src/jwt-cpp/build-auto SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  cmd_args_test_TESTS CmdArgsTest.EmptyArgs CmdArgsTest.LongOptionWithValue CmdArgsTest.LongOptionWithEquals CmdArgsTest.LongOptionEmptyValue CmdArgsTest.LongOptionWithoutValue CmdArgsTest.ShortOptionWithValue CmdArgsTest.ShortOptionWithEquals CmdArgsTest.ShortOptionEmptyValue CmdArgsTest.ShortOptionWithoutValue CmdArgsTest.GroupedShortOptions CmdArgsTest.PositionalArguments CmdArgsTest.MixedOptionsAndPositionals CmdArgsTest.DuplicateKeys CmdArgsTest.LongOptionWithSpacedEquals CmdArgsTest.ShortOptionWithSpacedEquals CmdArgsTest.ValueStartingWithDash CmdArgsTest.EmptyStringValue CmdArgsTest.MultipleOptionsAndValues CmdArgsTest.WhitespaceInValues CmdArgsTest.SpecialCharactersInValues CmdArgsTest.RealWorldExample_Generate CmdArgsTest.RealWorldExample_Sign CmdArgsTest.RealWorldExample_Verify CmdArgsTest.NonexistentOption CmdArgsTest.ConsistencyBetweenLongAndShortEquals)
